# Generated by Django 4.2.1 on 2023-06-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_counter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counter',
        ),
    ]
