# Generated by Django 4.2.1 on 2023-06-03 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_bicepshistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='shoulder_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ShoulderpressHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoulder_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.enrollment')),
            ],
        ),
    ]
