# Generated by Django 4.2.1 on 2023-06-03 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_enrollment_shoulder_count_shoulderpresshistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoulderpresshistory',
            old_name='enrollment',
            new_name='enrollment1',
        ),
    ]
