# Generated by Django 4.2.1 on 2023-06-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_rename_enrollment_shoulderpresshistory_enrollment1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoulderpresshistory',
            old_name='enrollment1',
            new_name='enrollment',
        ),
    ]
