# Generated by Django 4.2.1 on 2023-06-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_tricepshistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='side_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='squat_count',
            field=models.IntegerField(default=0),
        ),
    ]
