# Generated by Django 4.2.1 on 2023-06-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0019_rename_triceps_count_tricepshistory_triceps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tricepshistory',
            old_name='triceps',
            new_name='triceps_counter',
        ),
    ]
