# Generated by Django 4.2.1 on 2023-06-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0020_rename_triceps_tricepshistory_triceps_counter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tricepshistory',
            old_name='triceps_counter',
            new_name='side_count',
        ),
    ]
