# Generated by Django 4.2.1 on 2023-06-06 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0022_enrollment_pushup_count_pushuphistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='biceps_count',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='shoulder_count',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='squat_count',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='triceps_count',
        ),
    ]
