# Generated by Django 4.2.1 on 2023-06-06 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0025_alter_bicepshistory_enrollment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('bmi', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='biceps_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='shoulder_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='squat_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='triceps_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bicepshistory',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.enrollment'),
        ),
        migrations.AlterField(
            model_name='pushuphistory',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.enrollment'),
        ),
        migrations.AlterField(
            model_name='shoulderpresshistory',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.enrollment'),
        ),
        migrations.AlterField(
            model_name='squathistory',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.enrollment'),
        ),
        migrations.AlterField(
            model_name='tricepshistory',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.enrollment'),
        ),
    ]
