# Generated by Django 4.2.1 on 2023-06-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0027_alter_enrollment_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='FullName',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='PhoneNumber',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
